name: Run Python script with dynamic URIs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate matrix
      id: set-matrix
      run: echo "::set-output name=matrix::{\"uri\": $(cat uris.txt | jq -R -c 'split("\n")')}"

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        uri: ${{ fromJson(needs.setup.outputs.matrix).uri }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script
      run: python run.py ${{ matrix.uri }}

    - name: Commit and Push
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add generated JSON file"
          git push
