name: Run Python script with dynamic URIs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
   
    strategy:
      matrix:
        uri: ${{ fromJson(steps.get_uris.outputs.uris) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Get URIs
      id: get_uris
      run: echo "::set-output name=uris::$(bash read_uris.sh)"

    - name: Run script
      run: python run.py ${{ matrix.uri }}

    - name: Commit and Push
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub
          git add .
          git commit -m "Add generated JSON file"
          git push
