name: Run Python Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Reset configs directory
      run: |
        rm -rf configs
        mkdir configs
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If there are any dependencies in your project, add them here.

    - name: Run Script
      run: python run.py
      
    - name: Upload JSON files
      uses: actions/upload-artifact@v2
      with:
        name: JSON files
        path: /configs/*.json
 

    - name: Commit and Push
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add generated JSON file"
          git push

    - name: Combine JSON files
      run: python export.py
 
    - name: Upload Combined JSON file
      uses: actions/upload-artifact@v2
      with:
        name: Combined JSON file
        path: configs/combined.json

    - name: Export JSON
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Export JSON"
          git pull
          git push
